export const data  = [
  {
    "id": 1731801600000,
    "companyName": "Google",
    "jobTitle": "Frontend Developer",
    "location": "Remote",
    "salaryRange": "$120k-$150k",
    "applicationDate": "2024-11-01",
    "status": "Interview Scheduled",
    "applicationMethod": "LinkedIn",
    "jobLink": "https://careers.google.com/jobs/frontend-dev",
    "notes": "Applied through LinkedIn. HR reached out after 1 week. Technical interview scheduled for next Monday. Need to prepare React and system design questions.",
    "interviewDate": "2024-11-25"
  },
  {
    "id": 1731715200000,
    "companyName": "Meta",
    "jobTitle": "React Developer",
    "location": "Hybrid",
    "salaryRange": "$130k-$160k",
    "applicationDate": "2024-10-28",
    "status": "Interviewed",
    "applicationMethod": "Company Website",
    "jobLink": "https://metacareers.com/react-developer",
    "notes": "Completed 3 rounds: HR screening, technical coding challenge, and system design. Waiting for final decision. Interview went well, they seemed impressed with my portfolio projects.",
    "interviewDate": "2024-11-15"
  },
  {
    "id": 1731628800000,
    "companyName": "Amazon",
    "jobTitle": "Software Development Engineer",
    "location": "Onsite",
    "salaryRange": "$110k-$140k",
    "applicationDate": "2024-10-25",
    "status": "Rejected",
    "applicationMethod": "Job Board",
    "jobLink": "https://amazon.jobs/sde",
    "notes": "Applied via Indeed. Got rejection email after 2 weeks. They mentioned high competition for the role. Will try again in 6 months with more experience.",
    "interviewDate": ""
  },
  {
    "id": 1731542400000,
    "companyName": "Microsoft",
    "jobTitle": "Full Stack Developer",
    "location": "Remote",
    "salaryRange": "$115k-$145k",
    "applicationDate": "2024-10-22",
    "status": "Applied",
    "applicationMethod": "Company Website",
    "jobLink": "https://careers.microsoft.com/fullstack",
    "notes": "Submitted application with custom cover letter. No response yet. Following up this week.",
    "interviewDate": ""
  },
  {
    "id": 1731456000000,
    "companyName": "Netflix",
    "jobTitle": "UI/UX Engineer",
    "location": "Remote",
    "salaryRange": "$140k-$170k",
    "applicationDate": "2024-10-19",
    "status": "Offered",
    "applicationMethod": "Referral",
    "jobLink": "https://jobs.netflix.com/ui-engineer",
    "notes": "Got referral from college friend. Interview process was smooth. Received offer letter today! Salary: $155k + stock options. Need to respond by end of month.",
    "interviewDate": "2024-11-10"
  },
  {
    "id": 1731369600000,
    "companyName": "Apple",
    "jobTitle": "iOS Developer",
    "location": "Onsite",
    "salaryRange": "$125k-$155k",
    "applicationDate": "2024-10-16",
    "status": "Applied",
    "applicationMethod": "LinkedIn",
    "jobLink": "https://jobs.apple.com/ios-developer",
    "notes": "Dream company! Applied for iOS position. Hoping to hear back soon. Updated resume to highlight Swift and SwiftUI projects.",
    "interviewDate": ""
  },
  {
    "id": 1731283200000,
    "companyName": "Shopify",
    "jobTitle": "Backend Developer",
    "location": "Remote",
    "salaryRange": "$100k-$130k",
    "applicationDate": "2024-10-13",
    "status": "Interview Scheduled",
    "applicationMethod": "Company Website",
    "jobLink": "https://shopify.com/careers/backend",
    "notes": "HR screening completed. Technical round scheduled for next week. Focus areas: Ruby on Rails, database optimization, and API design.",
    "interviewDate": "2024-11-22"
  },
  {
    "id": 1731196800000,
    "companyName": "Stripe",
    "jobTitle": "Full Stack Engineer",
    "location": "Hybrid",
    "salaryRange": "$135k-$165k",
    "applicationDate": "2024-10-10",
    "status": "Interviewed",
    "applicationMethod": "Referral",
    "jobLink": "https://stripe.com/jobs/engineer",
    "notes": "Friend referred me. Had 4 interview rounds over 2 weeks. Coding challenges were tough but fair. Expecting response this week.",
    "interviewDate": "2024-11-08"
  },
  {
    "id": 1731110400000,
    "companyName": "Airbnb",
    "jobTitle": "Frontend Engineer",
    "location": "Remote",
    "salaryRange": "$120k-$150k",
    "applicationDate": "2024-10-07",
    "status": "Rejected",
    "applicationMethod": "LinkedIn",
    "jobLink": "https://careers.airbnb.com/frontend",
    "notes": "Applied but didn't pass initial screening. Feedback: need more experience with large-scale applications. Good learning experience.",
    "interviewDate": ""
  },
  {
    "id": 1731024000000,
    "companyName": "Spotify",
    "jobTitle": "Software Engineer",
    "location": "Hybrid",
    "salaryRange": "$110k-$140k",
    "applicationDate": "2024-10-04",
    "status": "Applied",
    "applicationMethod": "Job Board",
    "jobLink": "https://spotify.com/careers/engineer",
    "notes": "Applied via Glassdoor. Really excited about this one - love their product. Fingers crossed!",
    "interviewDate": ""
  },
  {
    "id": 1730937600000,
    "companyName": "Tesla",
    "jobTitle": "Embedded Software Engineer",
    "location": "Onsite",
    "salaryRange": "$105k-$135k",
    "applicationDate": "2024-10-01",
    "status": "Interview Scheduled",
    "applicationMethod": "Company Website",
    "jobLink": "https://tesla.com/careers/embedded",
    "notes": "Recruiter called yesterday. Phone screen went well. On-site interview next month. Need to brush up on C++ and embedded systems.",
    "interviewDate": "2024-12-05"
  },
  {
    "id": 1730851200000,
    "companyName": "Uber",
    "jobTitle": "Mobile Developer",
    "location": "Remote",
    "salaryRange": "$115k-$145k",
    "applicationDate": "2024-09-28",
    "status": "Rejected",
    "applicationMethod": "Recruiter",
    "jobLink": "https://uber.com/careers/mobile",
    "notes": "Recruiter reached out. After initial chat, they said they're looking for someone with more React Native experience. Fair enough.",
    "interviewDate": ""
  },
  {
    "id": 1730764800000,
    "companyName": "Adobe",
    "jobTitle": "Creative Cloud Engineer",
    "location": "Hybrid",
    "salaryRange": "$120k-$150k",
    "applicationDate": "2024-09-25",
    "status": "Applied",
    "applicationMethod": "LinkedIn",
    "jobLink": "https://adobe.com/careers/creative-cloud",
    "notes": "Really interested in working on Creative Cloud products. Application submitted with portfolio showcasing design-focused projects.",
    "interviewDate": ""
  },
  {
    "id": 1730678400000,
    "companyName": "Salesforce",
    "jobTitle": "Cloud Platform Developer",
    "location": "Remote",
    "salaryRange": "$125k-$155k",
    "applicationDate": "2024-09-22",
    "status": "Interviewed",
    "applicationMethod": "Company Website",
    "jobLink": "https://salesforce.com/careers/developer",
    "notes": "Completed technical assessment and 2 interview rounds. Team seems great. Final round with VP scheduled next week. Very positive vibes!",
    "interviewDate": "2024-11-18"
  },
  {
    "id": 1730592000000,
    "companyName": "LinkedIn",
    "jobTitle": "Backend Engineer",
    "location": "Hybrid",
    "salaryRange": "$130k-$160k",
    "applicationDate": "2024-09-19",
    "status": "Offered",
    "applicationMethod": "Referral",
    "jobLink": "https://linkedin.com/careers/backend",
    "notes": "Former colleague referred me. Interview process was excellent - 3 rounds focused on system design and coding. Received competitive offer: $145k base + bonus + equity. Considering between this and Netflix offer.",
    "interviewDate": "2024-11-05"
  }
]